server: 
  port: 8085
title: Welcome visit TRADE-SERVICE!
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://172.16.0.3/gccx
    password: 1qaz@WSX
  jpa:
    show-sql: true
